diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
http.postbuffer=1048576000
user.name=cryptoking110600
user.email=cryptoking110600.gmail.com
push.autosetupremote=true
safe.directory=F:/Project/3 Project/2025✔✔✔✔/meme sniper bot(mumper)
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/cryptoking110600/Raydium-pumpswap-sniper-bot-using-jito.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
